// 正式問題72問の確定データ
// 誤答・科目・分類・解説は最終採用値を直接保持する
const OFFICIAL_QUESTIONS=[
  {
    "id": 10001,
    "stableId": "追加-001",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "生活衛生関係営業",
    "q": "生活衛生関係営業の適正化及び振興に関する法律の目的に最も近いものはどれか。",
    "choices": [
      "営業者の自主的活動を促進し、経営の健全化と衛生水準の維持向上を図る",
      "営業者間の競争を制限し、営業地域ごとの料金を統一する",
      "営業施設の国による設置を進め、営業者へ運営を委託する",
      "営業者の資格要件を全国で統一し、免許制度を一元管理する"
    ],
    "answer": 0,
    "explanation": "同法は、営業者の組織の自主的活動を促進し、経営の健全化、衛生施設の改善向上等を通じて公衆衛生の向上・増進と国民生活の安定に寄与する法律である。",
    "difficulty": "標準",
    "sourceName": "ｅ－Ｇｏｖ法令検索「生活衛生関係営業の運営の適正化及び振興に関する法律」",
    "sourceUrl": "https://laws.e-gov.go.jp/law/332AC1000000164",
    "category": "barber_act",
    "point": "ｅ－Ｇｏｖ法令検索「生活衛生関係営業の運営の適正化及び振興に関する法律」",
    "exp": "同法は、営業者の組織の自主的活動を促進し、経営の健全化、衛生施設の改善向上等を通じて公衆衛生の向上・増進と国民生活の安定に寄与する法律である。",
    "themeId": "official_regulations_生活衛生関係営業"
  },
  {
    "id": 10002,
    "stableId": "追加-002",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "生活衛生同業組合",
    "q": "生活衛生同業組合について正しいものはどれか。",
    "choices": [
      "同一業種の営業者が加入を義務付けられる法人である",
      "同一業種の営業者が自主的に組織する法人である",
      "複数業種の従業者だけが組織する任意団体である",
      "地方公共団体が営業者を構成員として設置する行政機関である"
    ],
    "answer": 1,
    "explanation": "生活衛生同業組合は、同一の生活衛生関係営業の営業者が自主的に組織する法人であり、加入が一律に強制される行政機関ではない。",
    "difficulty": "標準",
    "sourceName": "全国生活衛生営業指導センター「生活衛生同業組合」",
    "sourceUrl": "https://www.seiei.or.jp/",
    "category": "barber_act",
    "point": "全国生活衛生営業指導センター「生活衛生同業組合」",
    "exp": "生活衛生同業組合は、同一の生活衛生関係営業の営業者が自主的に組織する法人であり、加入が一律に強制される行政機関ではない。",
    "themeId": "official_regulations_生活衛生同業組合"
  },
  {
    "id": 10003,
    "stableId": "追加-003",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "振興計画",
    "q": "生活衛生関係営業の振興計画の主な役割として適切なものはどれか。",
    "choices": [
      "営業者ごとの施術料金と営業時間を一律に定める基準となる",
      "組合員に対する営業許可と免許交付を行う根拠となる",
      "業界の振興に必要な事業を計画的に進める指針となる",
      "地域ごとの理容所数を制限する配置計画となる"
    ],
    "answer": 2,
    "explanation": "振興計画は、営業の振興を計画的に進めるための事業内容を定めるもので、免許や開設届の処理を行うものではない。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「生活衛生関係営業の振興」",
    "sourceUrl": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000123858.html",
    "category": "barber_act",
    "point": "厚生労働省「生活衛生関係営業の振興」",
    "exp": "振興計画は、営業の振興を計画的に進めるための事業内容を定めるもので、免許や開設届の処理を行うものではない。",
    "themeId": "official_regulations_振興計画"
  },
  {
    "id": 10004,
    "stableId": "追加-004",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "政策金融",
    "q": "日本政策金融公庫の生活衛生貸付の説明として適切なものはどれか。",
    "choices": [
      "生活衛生関係営業者の運転資金だけを無利子で給付する制度である",
      "生活衛生同業組合が営業者の納税を免除する制度である",
      "設備改善を行った営業者へ費用の全額を補助する制度である",
      "生活衛生関係営業者の設備資金等の調達を支援する制度である"
    ],
    "answer": 3,
    "explanation": "生活衛生貸付は、生活衛生関係営業者の設備資金等を融資によって支援する。免許・試験・消毒薬配布の制度ではない。",
    "difficulty": "標準",
    "sourceName": "日本政策金融公庫「生活衛生貸付」",
    "sourceUrl": "https://www.jfc.go.jp/n/finance/search/seikatsu.html",
    "category": "barber_act",
    "point": "日本政策金融公庫「生活衛生貸付」",
    "exp": "生活衛生貸付は、生活衛生関係営業者の設備資金等を融資によって支援する。免許・試験・消毒薬配布の制度ではない。",
    "themeId": "official_regulations_政策金融"
  },
  {
    "id": 10005,
    "stableId": "追加-005",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "廃棄物処理",
    "q": "廃棄物処理の基本原則として適切なものはどれか。",
    "choices": [
      "事業活動に伴う廃棄物は、事業者が適正に処理する責任を負う",
      "事業活動に伴う廃棄物は、市町村が一律に処理責任を負う",
      "事業活動に伴う廃棄物は、処理業者へ渡した時点で事業者の責任がなくなる",
      "事業活動に伴う廃棄物は、量が少なければ家庭廃棄物として扱う"
    ],
    "answer": 0,
    "explanation": "廃棄物処理法は、事業者に事業活動に伴って生じた廃棄物を自らの責任で適正に処理する責務を定めている。",
    "difficulty": "標準",
    "sourceName": "ｅ－Ｇｏｖ法令検索「廃棄物の処理及び清掃に関する法律」",
    "sourceUrl": "https://laws.e-gov.go.jp/law/345AC0000000137",
    "category": "barber_act",
    "point": "ｅ－Ｇｏｖ法令検索「廃棄物の処理及び清掃に関する法律」",
    "exp": "廃棄物処理法は、事業者に事業活動に伴って生じた廃棄物を自らの責任で適正に処理する責務を定めている。",
    "themeId": "official_regulations_廃棄物処理"
  },
  {
    "id": 10006,
    "stableId": "追加-006",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "一般廃棄物・産業廃棄物",
    "q": "事業所から出る廃棄物の取扱いについて正しいものはどれか。",
    "choices": [
      "事業所から生じたものは、種類にかかわらずすべて産業廃棄物とする",
      "種類と性状に応じて一般廃棄物か産業廃棄物かを判断する",
      "事業所から生じたものは、量が一定以下ならすべて一般廃棄物とする",
      "事業所から生じたものは、固体を一般廃棄物、液体を産業廃棄物とする"
    ],
    "answer": 1,
    "explanation": "事業系廃棄物は、排出場所だけで一律に決まらず、法令上の種類と性状により一般廃棄物又は産業廃棄物に区分される。",
    "difficulty": "やや難",
    "sourceName": "環境省「廃棄物処理法」",
    "sourceUrl": "https://www.env.go.jp/recycle/waste/laws.html",
    "category": "barber_act",
    "point": "環境省「廃棄物処理法」",
    "exp": "事業系廃棄物は、排出場所だけで一律に決まらず、法令上の種類と性状により一般廃棄物又は産業廃棄物に区分される。",
    "themeId": "official_regulations_一般廃棄物・産業廃棄物"
  },
  {
    "id": 10007,
    "stableId": "追加-007",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "理容師法と美容師法",
    "q": "理容と美容の法令上の定義の違いとして正しいものはどれか。",
    "choices": [
      "理容は容姿を美しくすること、美容は容姿を整えることを中心に定義される",
      "理容は頭髪だけ、美容は顔面だけを対象として定義される",
      "理容は容姿を整えること、美容は容姿を美しくすることを中心に定義される",
      "理容は刈込みだけ、美容はパーマネントウェーブだけを対象として定義される"
    ],
    "answer": 2,
    "explanation": "理容師法は頭髪の刈込、顔そり等により容姿を整えること、美容師法はパーマネントウェーブ、結髪、化粧等により容姿を美しくすることを定義の中心とする。",
    "difficulty": "標準",
    "sourceName": "ｅ－Ｇｏｖ法令検索「理容師法」「美容師法」",
    "sourceUrl": "https://laws.e-gov.go.jp/law/322AC0000000234",
    "category": "barber_act",
    "point": "ｅ－Ｇｏｖ法令検索「理容師法」「美容師法」",
    "exp": "理容師法は頭髪の刈込、顔そり等により容姿を整えること、美容師法はパーマネントウェーブ、結髪、化粧等により容姿を美しくすることを定義の中心とする。",
    "themeId": "official_regulations_理容師法と美容師法"
  },
  {
    "id": 10008,
    "stableId": "追加-008",
    "status": "approved",
    "subjectId": "regulations",
    "subjectName": "関係法規・制度",
    "field": "衛生行政",
    "q": "国と地方公共団体の衛生行政について適切なものはどれか。",
    "choices": [
      "国が衛生行政を一元的に担い、地方公共団体は実施に関与しない",
      "地方公共団体が衛生行政を一元的に担い、国は基準設定に関与しない",
      "国は理容所の監視だけ、地方公共団体は免許交付だけを担う",
      "国と地方公共団体は、それぞれの権限と役割に基づいて衛生行政を担う"
    ],
    "answer": 3,
    "explanation": "衛生行政は国と地方公共団体が法令に基づく役割分担の下で実施し、保健所は地域保健の中核的機関として理容業とも関わる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・関係法規",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "barber_act",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・関係法規",
    "exp": "衛生行政は国と地方公共団体が法令に基づく役割分担の下で実施し、保健所は地域保健の中核的機関として理容業とも関わる。",
    "themeId": "official_regulations_衛生行政"
  },
  {
    "id": 10009,
    "stableId": "追加-009",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "採光・照明",
    "q": "理容所の照明管理として適切なものはどれか。",
    "choices": [
      "作業面に必要な明るさを確保し、まぶしさや影にも配慮する",
      "室内全体の照度だけを高くし、作業面の影は考慮しない",
      "作業面の明るさより、客席から見た装飾効果を優先する",
      "自然光を主とし、時間帯による作業面の明るさの変化は考慮しない"
    ],
    "answer": 0,
    "explanation": "安全で正確な施術には、作業面の十分な明るさと、まぶしさ・影を抑えた見やすい環境が必要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "安全で正確な施術には、作業面の十分な明るさと、まぶしさ・影を抑えた見やすい環境が必要である。",
    "themeId": "official_hygiene_採光・照明"
  },
  {
    "id": 10010,
    "stableId": "追加-010",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "換気",
    "q": "理容所の換気の目的として最も適切なものはどれか。",
    "choices": [
      "室温だけを下げ、室内の空気は外へ排出しない",
      "汚染された空気を排出し、新鮮な空気と入れ替える",
      "室内の空気を循環させ、外気との入替えは行わない",
      "湿度だけを一定にし、臭気や浮遊物質は室内に保持する"
    ],
    "answer": 1,
    "explanation": "換気は、二酸化炭素、臭気、湿気、浮遊物質などを含む室内空気を排出し、新鮮な空気に入れ替えるために行う。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "換気は、二酸化炭素、臭気、湿気、浮遊物質などを含む室内空気を排出し、新鮮な空気に入れ替えるために行う。",
    "themeId": "official_hygiene_換気"
  },
  {
    "id": 10011,
    "stableId": "追加-011",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "床・構造設備",
    "q": "理容所の床の衛生管理として適切なものはどれか。",
    "choices": [
      "清掃回数を減らすため、床面を吸水性の高い材料にする",
      "汚れを目立たなくするため、凹凸の多い暗色の床面にする",
      "清掃しやすく、汚れや水分を除去しやすい状態を保つ",
      "水分の蒸発を待つため、清掃後も濡れた状態を保つ"
    ],
    "answer": 2,
    "explanation": "床は毛髪や汚れがたまりやすいため、清掃・除去しやすく、衛生的に保てる構造と管理が重要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "床は毛髪や汚れがたまりやすいため、清掃・除去しやすく、衛生的に保てる構造と管理が重要である。",
    "themeId": "official_hygiene_床・構造設備"
  },
  {
    "id": 10012,
    "stableId": "追加-012",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "衣服衛生",
    "q": "施術者の作業衣の管理として適切なものはどれか。",
    "choices": [
      "目に見える汚れがない限り、同じ作業衣を継続して着用する",
      "作業衣が汚染した場合は、営業終了後にまとめて交換する",
      "使用済み作業衣と清潔な作業衣を同じ場所に重ねて保管する",
      "清潔なものを着用し、汚染した場合は交換する"
    ],
    "answer": 3,
    "explanation": "作業衣や布片類は清潔に保ち、汚染時には交換する。清潔なものと使用済みのものを区別して扱うことも重要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "作業衣や布片類は清潔に保ち、汚染時には交換する。清潔なものと使用済みのものを区別して扱うことも重要である。",
    "themeId": "official_hygiene_衣服衛生"
  },
  {
    "id": 10013,
    "stableId": "追加-013",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "廃棄物",
    "q": "理容所で生じた毛髪などの廃棄物の管理として適切なものはどれか。",
    "choices": [
      "飛散や悪臭を防ぐように収集し、適切に処理する",
      "毛髪は乾燥しているため、開放容器に収集して営業終了後に処理する",
      "毛髪は排水とともに流し、排水設備内でまとめて回収する",
      "毛髪は飛散を防ぐため、床面を湿らせたまま集積して保管する"
    ],
    "answer": 0,
    "explanation": "廃棄物は作業環境を汚染しないよう収集し、飛散・悪臭・害虫発生を防いで適切に処理する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "廃棄物は作業環境を汚染しないよう収集し、飛散・悪臭・害虫発生を防いで適切に処理する。",
    "themeId": "official_hygiene_廃棄物"
  },
  {
    "id": 10014,
    "stableId": "追加-014",
    "status": "approved",
    "subjectId": "hygiene",
    "subjectName": "衛生管理",
    "field": "清潔・不潔の区分",
    "q": "使用済み器具と消毒済み器具の管理として適切なものはどれか。",
    "choices": [
      "外観で識別できるよう、同じ保管容器の中で位置だけを分ける",
      "交差汚染を防ぐため、区別して保管する",
      "使用済み器具を洗浄した時点で、消毒済み器具と一緒に保管する",
      "消毒済み器具を使用済み器具の上に置き、同じ容器で保管する"
    ],
    "answer": 1,
    "explanation": "使用済み器具と消毒済み器具を区別し、再汚染を防ぐことは衛生管理の基本である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "public_health",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・衛生管理",
    "exp": "使用済み器具と消毒済み器具を区別し、再汚染を防ぐことは衛生管理の基本である。",
    "themeId": "official_hygiene_清潔・不潔の区分"
  },
  {
    "id": 10015,
    "stableId": "追加-015",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "頭部の骨格",
    "q": "頭蓋骨の主な役割として正しいものはどれか。",
    "choices": [
      "脳を保護し、上肢の運動の支点をつくる",
      "脊髄を保護し、胸郭の骨格をつくる",
      "脳を保護し、顔面の骨格をつくる",
      "顔面を保護し、下肢の運動の支点をつくる"
    ],
    "answer": 2,
    "explanation": "頭蓋骨は脳を保護するとともに、顔面の形態をつくる骨格となる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "頭蓋骨は脳を保護するとともに、顔面の形態をつくる骨格となる。",
    "themeId": "official_health_頭部の骨格"
  },
  {
    "id": 10016,
    "stableId": "追加-016",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "顔面の骨格",
    "q": "下顎骨について正しいものはどれか。",
    "choices": [
      "頭蓋骨の中で大きく動く骨で、眼球運動に関与する",
      "頭蓋骨の中で動かない骨で、咀嚼に関与する",
      "頭蓋骨とは関節せず、舌の運動だけに関与する",
      "頭蓋骨の中で大きく動く骨で、咀嚼に関与する"
    ],
    "answer": 3,
    "explanation": "下顎骨は顎関節を介して運動し、咀嚼や発音などに関与する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "下顎骨は顎関節を介して運動し、咀嚼や発音などに関与する。",
    "themeId": "official_health_顔面の骨格"
  },
  {
    "id": 10017,
    "stableId": "追加-017",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "頸部の骨格",
    "q": "頸椎の役割として適切なものはどれか。",
    "choices": [
      "頭部を支え、頸部の運動に関与する",
      "頭部を支え、下顎の挙上に関与する",
      "頭部を支え、表情筋の運動に関与する",
      "胸郭を支え、頸部の知覚に関与する"
    ],
    "answer": 0,
    "explanation": "頸椎は頭部を支え、屈曲・伸展・回旋など頸部の運動に関与する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "頸椎は頭部を支え、屈曲・伸展・回旋など頸部の運動に関与する。",
    "themeId": "official_health_頸部の骨格"
  },
  {
    "id": 10018,
    "stableId": "追加-018",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "表情筋",
    "q": "表情筋の特徴として正しいものはどれか。",
    "choices": [
      "骨と骨を結び、関節を動かして表情をつくる",
      "皮膚を動かして表情をつくる",
      "下顎骨だけを動かし、咀嚼による表情をつくる",
      "皮膚には付着せず、眼球だけを動かして表情をつくる"
    ],
    "answer": 1,
    "explanation": "表情筋は顔面の皮膚に付着し、その収縮によって表情をつくる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "表情筋は顔面の皮膚に付着し、その収縮によって表情をつくる。",
    "themeId": "official_health_表情筋"
  },
  {
    "id": 10019,
    "stableId": "追加-019",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "咀嚼筋",
    "q": "咬筋の主な作用はどれか。",
    "choices": [
      "下顎を下制して口を開く",
      "口角を外側へ引いて口裂を広げる",
      "下顎を挙上して口を閉じる",
      "下唇を引き下げて口を開く"
    ],
    "answer": 2,
    "explanation": "咬筋は代表的な咀嚼筋で、下顎骨を挙上し、歯をかみ合わせる働きをする。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "咬筋は代表的な咀嚼筋で、下顎骨を挙上し、歯をかみ合わせる働きをする。",
    "themeId": "official_health_咀嚼筋"
  },
  {
    "id": 10020,
    "stableId": "追加-020",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "頸部の筋",
    "q": "胸鎖乳突筋の作用として適切なものはどれか。",
    "choices": [
      "両側の収縮で頸部を伸展するだけで、回旋には関与しない",
      "片側の収縮で頸部を同側へ回旋する",
      "下顎を挙上し、口を閉じる運動に関与する",
      "頸部の屈曲や回旋に関与する"
    ],
    "answer": 3,
    "explanation": "胸鎖乳突筋は頭部・頸部の屈曲や回旋などに関与する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "胸鎖乳突筋は頭部・頸部の屈曲や回旋などに関与する。",
    "themeId": "official_health_頸部の筋"
  },
  {
    "id": 10021,
    "stableId": "追加-021",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "顔面神経",
    "q": "顔面神経の機能として最も関係が深いものはどれか。",
    "choices": [
      "表情筋の運動",
      "顔面皮膚の知覚と咀嚼筋の運動",
      "舌の運動と味覚のすべて",
      "頸部筋の運動と頭皮の知覚"
    ],
    "answer": 0,
    "explanation": "顔面神経は表情筋の運動を支配する。顔面施術では神経の走行と働きを理解することが重要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "顔面神経は表情筋の運動を支配する。顔面施術では神経の走行と働きを理解することが重要である。",
    "themeId": "official_health_顔面神経"
  },
  {
    "id": 10022,
    "stableId": "追加-022",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "三叉神経",
    "q": "三叉神経の主な働きとして正しいものはどれか。",
    "choices": [
      "顔面の表情筋の運動だけに関与する",
      "顔面の知覚と咀嚼筋の運動に関与する",
      "顔面の知覚と舌筋の運動に関与する",
      "顔面の知覚と眼球運動に関与する"
    ],
    "answer": 1,
    "explanation": "三叉神経は顔面の知覚を伝えるとともに、その一部は咀嚼筋の運動を担う。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "human_body",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "三叉神経は顔面の知覚を伝えるとともに、その一部は咀嚼筋の運動を担う。",
    "themeId": "official_health_三叉神経"
  },
  {
    "id": 10023,
    "stableId": "追加-023",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "接触皮膚炎",
    "q": "香粧品による接触皮膚炎が疑われる客への対応として適切なものはどれか。",
    "choices": [
      "原因が疑われる製品を少量にして施術を継続し、経過を見る",
      "症状部位を洗浄した後、別の同種製品へ替えて施術を続ける",
      "原因が疑われる製品の使用を中止し、必要に応じ受診を勧める",
      "症状が軽ければ施術を終え、次回来店時まで受診を勧めない"
    ],
    "answer": 2,
    "explanation": "発赤やかゆみ等が出た場合は原因が疑われる製品の使用を中止し、症状に応じて医療機関への相談を勧める。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "skin",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "発赤やかゆみ等が出た場合は原因が疑われる製品の使用を中止し、症状に応じて医療機関への相談を勧める。",
    "themeId": "official_health_接触皮膚炎"
  },
  {
    "id": 10024,
    "stableId": "追加-024",
    "status": "approved",
    "subjectId": "health",
    "subjectName": "保健",
    "field": "アレルギー",
    "q": "アレルギー性接触皮膚炎の説明として適切なものはどれか。",
    "choices": [
      "特定物質への初回接触時に、感作を経ず必ず発症する",
      "特定物質の刺激の強さだけで起こり、免疫反応は関与しない",
      "特定物質に感作されても、再接触では症状を生じない",
      "特定物質に感作された後、再接触により免疫反応が起こることがある"
    ],
    "answer": 3,
    "explanation": "アレルギー性接触皮膚炎は、感作の成立後に原因物質へ再接触することで免疫反応が起こり、湿疹等を生じることがある。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "skin",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・保健",
    "exp": "アレルギー性接触皮膚炎は、感作の成立後に原因物質へ再接触することで免疫反応が起こり、湿疹等を生じることがある。",
    "themeId": "official_health_アレルギー"
  },
  {
    "id": 10025,
    "stableId": "追加-025",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "溶液の調製",
    "q": "濃い溶液を薄めて所定濃度の溶液を作るとき、基本となる考え方はどれか。",
    "choices": [
      "溶質量の関係を保ちながら、必要な溶媒量を計算する",
      "最終体積だけを一定にし、溶質量の変化は考慮しない",
      "原液量だけを一定にし、溶媒量にかかわらず同じ濃度とする",
      "希釈前後の濃度だけを等しくし、体積の関係は考慮しない"
    ],
    "answer": 0,
    "explanation": "希釈では、希釈前後の溶質量の関係を基に計算し、製品表示や手順に従って正確に調製する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "希釈では、希釈前後の溶質量の関係を基に計算し、製品表示や手順に従って正確に調製する。",
    "themeId": "official_cosmetic_chemistry_溶液の調製"
  },
  {
    "id": 10026,
    "stableId": "追加-026",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "薬品の取扱い",
    "q": "化学薬品の取扱いとして適切なものはどれか。",
    "choices": [
      "同じ用途の薬品なら、表示濃度にかかわらず同量を使用する",
      "表示と使用上の注意を確認し、定められた方法で扱う",
      "表示が読めない場合は、色とにおいから薬品を判別して使用する",
      "作用を強める場合は、表示にない薬品も同じ容器で混合する"
    ],
    "answer": 1,
    "explanation": "誤使用や混合事故を防ぐため、表示・濃度・使用期限・注意事項を確認し、所定の方法で保管・使用する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "誤使用や混合事故を防ぐため、表示・濃度・使用期限・注意事項を確認し、所定の方法で保管・使用する。",
    "themeId": "official_cosmetic_chemistry_薬品の取扱い"
  },
  {
    "id": 10027,
    "stableId": "追加-027",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "整髪料",
    "q": "整髪料の主な目的として最も適切なものはどれか。",
    "choices": [
      "毛髪表面の汚れを除去し、頭皮を洗浄する",
      "毛髪内部のメラニンを分解し、明度を上げる",
      "毛髪の形を整え、保持し、つやや質感を与える",
      "毛髪内部の結合を切断し、ウェーブを形成する"
    ],
    "answer": 2,
    "explanation": "整髪料は、毛髪をまとめたり形を保持したりし、つや・質感を調整するために用いる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "整髪料は、毛髪をまとめたり形を保持したりし、つや・質感を調整するために用いる。",
    "themeId": "official_cosmetic_chemistry_整髪料"
  },
  {
    "id": 10028,
    "stableId": "追加-028",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "整髪料の種類",
    "q": "油性整髪料の一般的な特徴として適切なものはどれか。",
    "choices": [
      "水分を多く含み、乾燥後は軽い仕上がりになりやすい",
      "被膜をつくって強く固定し、乾燥後につやを抑えやすい",
      "粉体が皮脂を吸着し、乾いた質感を与えやすい",
      "つややまとまりを与えやすい"
    ],
    "answer": 3,
    "explanation": "油性基剤を含む整髪料は、毛髪につやとまとまりを与えやすい。脱色や酸化染毛のための製品ではない。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "油性基剤を含む整髪料は、毛髪につやとまとまりを与えやすい。脱色や酸化染毛のための製品ではない。",
    "themeId": "official_cosmetic_chemistry_整髪料の種類"
  },
  {
    "id": 10029,
    "stableId": "追加-029",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "養毛剤",
    "q": "養毛剤の使用について適切なものはどれか。",
    "choices": [
      "製品の表示と用法・用量を守り、頭皮に異常があれば使用を中止する",
      "表示量より多く使用すれば、頭皮状態にかかわらず効果が高まる",
      "頭皮に異常がある場合は、使用量を減らして継続する",
      "用法は製品間で共通なので、表示を確認せず同じ方法で使用する"
    ],
    "answer": 0,
    "explanation": "養毛剤は表示された使用方法を守り、刺激や発赤等の異常が生じた場合は使用を中止する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "養毛剤は表示された使用方法を守り、刺激や発赤等の異常が生じた場合は使用を中止する。",
    "themeId": "official_cosmetic_chemistry_養毛剤"
  },
  {
    "id": 10030,
    "stableId": "追加-030",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "品質管理",
    "q": "香粧品の品質を保つ取扱いとして適切なものはどれか。",
    "choices": [
      "開封後も未開封品と同じ期限まで使用できるため、開封時期は記録しない",
      "高温・直射日光・汚染を避け、表示された保管方法に従う",
      "品質を均一にするため、残量の少ない容器へ新しい製品を継ぎ足す",
      "分離が見られた製品は、十分に振れば表示期限後も使用できる"
    ],
    "answer": 1,
    "explanation": "品質低下や微生物汚染を防ぐため、密栓し、温度・光・清潔に配慮し、表示に従って保管する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "品質低下や微生物汚染を防ぐため、密栓し、温度・光・清潔に配慮し、表示に従って保管する。",
    "themeId": "official_cosmetic_chemistry_品質管理"
  },
  {
    "id": 10031,
    "stableId": "追加-031",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "酸化還元",
    "q": "酸化と還元の関係について正しいものはどれか。",
    "choices": [
      "酸化される物質がある反応では、他方も必ず酸化される",
      "還元される物質がある反応では、電子の移動は起こらない",
      "一方が酸化される反応では、他方が還元される",
      "酸化と還元は別々に起こり、同じ反応内では同時に進まない"
    ],
    "answer": 2,
    "explanation": "酸化還元反応では電子の授受が対応して起こり、一方の酸化と他方の還元が同時に進む。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "酸化還元反応では電子の授受が対応して起こり、一方の酸化と他方の還元が同時に進む。",
    "themeId": "official_cosmetic_chemistry_酸化還元"
  },
  {
    "id": 10032,
    "stableId": "追加-032",
    "status": "approved",
    "subjectId": "cosmetic_chemistry",
    "subjectName": "香粧品化学",
    "field": "安全性",
    "q": "初めて使用する香粧品の安全確認として適切なものはどれか。",
    "choices": [
      "同じ用途の製品を使用した経験があれば、成分確認は省略する",
      "少量使用なら異常は起こらないため、皮膚状態の確認は省略する",
      "注意事項は異常発生後に確認し、使用前は仕上がりだけを確認する",
      "成分、使用対象、注意事項を確認し、必要な事前確認を行う"
    ],
    "answer": 3,
    "explanation": "安全な施術には、製品表示、禁忌・注意事項、客の皮膚状態や過去の異常反応を確認することが必要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cosmetics",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・香粧品化学",
    "exp": "安全な施術には、製品表示、禁忌・注意事項、客の皮膚状態や過去の異常反応を確認することが必要である。",
    "themeId": "official_cosmetic_chemistry_安全性"
  },
  {
    "id": 10033,
    "stableId": "追加-033",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "海外理容文化史",
    "q": "古代社会における髪型やひげの役割として適切なものはどれか。",
    "choices": [
      "身分、宗教、職業などを示す意味を持つことがあった",
      "身分を示す意味はあったが、宗教や職業とは関係しなかった",
      "宗教を示す意味はあったが、身分や職業とは関係しなかった",
      "職業を示す意味はあったが、身分や宗教とは関係しなかった"
    ],
    "answer": 0,
    "explanation": "髪型やひげは、時代・地域により身分、宗教、職業、所属等を表す文化的記号として機能した。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "髪型やひげは、時代・地域により身分、宗教、職業、所属等を表す文化的記号として機能した。",
    "themeId": "official_culture_海外理容文化史"
  },
  {
    "id": 10034,
    "stableId": "追加-034",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "海外理容文化史",
    "q": "理容文化史を学ぶ意義として最も適切なものはどれか。",
    "choices": [
      "各時代の髪型を年代順に暗記し、社会背景とは切り離して理解する",
      "髪型や服飾と社会・文化の関係を理解し、現代の表現に生かす",
      "過去の技術をそのまま再現し、現代の生活様式への適合は考えない",
      "現代の流行だけを理解し、過去から続く造形や価値観は扱わない"
    ],
    "answer": 1,
    "explanation": "文化史の学習は、髪型・服飾が社会背景や美意識と結び付いて変化してきたことを理解し、現代の提案に生かすために行う。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "文化史の学習は、髪型・服飾が社会背景や美意識と結び付いて変化してきたことを理解し、現代の提案に生かすために行う。",
    "themeId": "official_culture_海外理容文化史"
  },
  {
    "id": 10035,
    "stableId": "追加-035",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "流行心理",
    "q": "流行が広がる要因として適切なものはどれか。",
    "choices": [
      "他者と同じでありたい心理だけが働き、差別化の心理は働かない",
      "他者と異なりたい心理だけが働き、同調の心理は働かない",
      "同調したい心理と他者と差別化したい心理の双方が働くことがある",
      "個人の心理より法令による強制が中心となって広がる"
    ],
    "answer": 2,
    "explanation": "流行には、集団への同調、個性化、情報伝達、社会状況など複数の要因が関わる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "流行には、集団への同調、個性化、情報伝達、社会状況など複数の要因が関わる。",
    "themeId": "official_culture_流行心理"
  },
  {
    "id": 10036,
    "stableId": "追加-036",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "流行と理容業",
    "q": "流行が理容業で持つ役割として適切なものはどれか。",
    "choices": [
      "流行をそのまま全客へ再現し、個人差をなくす基準となる",
      "流行技術だけを優先し、既存技術を用いない判断基準となる",
      "客の要望より流行を優先し、同じ提案を行う根拠となる",
      "客の要望や社会の美意識を捉え、技術提案に反映する手掛かりとなる"
    ],
    "answer": 3,
    "explanation": "流行の理解は客の希望や社会的な美意識を読み取り、個人に適した提案へつなげるために役立つ。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "流行の理解は客の希望や社会的な美意識を読み取り、個人に適した提案へつなげるために役立つ。",
    "themeId": "official_culture_流行と理容業"
  },
  {
    "id": 10037,
    "stableId": "追加-037",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "服飾の原理",
    "q": "服飾と髪型の調和を考える際に適切な視点はどれか。",
    "choices": [
      "形、色、素材、場面、着用者の個性を総合して考える",
      "形と色だけを合わせ、素材や場面は別に考える",
      "流行と季節だけを合わせ、着用者の個性は考慮しない",
      "髪型と服装を別々に決め、全体の比例や調和は最後に考える"
    ],
    "answer": 0,
    "explanation": "理容デザインでは、髪型と服飾の形・色・素材、着用場面、本人の個性との調和を総合的に考える。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "理容デザインでは、髪型と服飾の形・色・素材、着用場面、本人の個性との調和を総合的に考える。",
    "themeId": "official_culture_服飾の原理"
  },
  {
    "id": 10038,
    "stableId": "追加-038",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "衣服の種類",
    "q": "衣服を選ぶ際の基本として適切なものはどれか。",
    "choices": [
      "目的と季節を優先し、場所や相手との関係は考慮しない",
      "目的、季節、場所、相手との関係に配慮する",
      "場所と相手との関係を優先し、季節や機能性は考慮しない",
      "流行と個性を優先し、目的や場所への適合は考慮しない"
    ],
    "answer": 1,
    "explanation": "衣服は機能性だけでなく、時・場所・場合や相手との関係、季節、目的に応じて選ぶ。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "衣服は機能性だけでなく、時・場所・場合や相手との関係、季節、目的に応じて選ぶ。",
    "themeId": "official_culture_衣服の種類"
  },
  {
    "id": 10039,
    "stableId": "追加-039",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "服飾エチケット",
    "q": "冠婚葬祭など改まった場での服装について適切なものはどれか。",
    "choices": [
      "場の目的に合えば、清潔感や全体の調和は問われない",
      "慣習に合えば、着用者への適合や清潔感は問われない",
      "場の目的と慣習に配慮し、清潔で調和のある装いを選ぶ",
      "清潔であれば、場の目的や慣習への配慮は問われない"
    ],
    "answer": 2,
    "explanation": "服飾エチケットでは、場の目的、慣習、相手への敬意、清潔感、全体の調和を考える。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "服飾エチケットでは、場の目的、慣習、相手への敬意、清潔感、全体の調和を考える。",
    "themeId": "official_culture_服飾エチケット"
  },
  {
    "id": 10040,
    "stableId": "追加-040",
    "status": "approved",
    "subjectId": "culture",
    "subjectName": "文化論",
    "field": "人間美",
    "q": "理容における人間美の創造について適切なものはどれか。",
    "choices": [
      "客の個性より流行との一致を優先し、技術で統一的に表現する",
      "客の生活より造形上の完成度を優先し、安全性は別に判断する",
      "客の要望をそのまま再現し、技術的・美的な調整は行わない",
      "技術と美的感覚を用い、客の個性や生活に調和する表現を目指す"
    ],
    "answer": 3,
    "explanation": "理容は、確かな技術、美的感覚、安全・衛生への配慮を基に、客の個性や生活に調和する容姿を整える。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "history",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・文化論",
    "exp": "理容は、確かな技術、美的感覚、安全・衛生への配慮を基に、客の個性や生活に調和する容姿を整える。",
    "themeId": "official_culture_人間美"
  },
  {
    "id": 10041,
    "stableId": "追加-041",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "経営戦略",
    "q": "理容所の経営戦略を考える際に最初に行うこととして適切なものはどれか。",
    "choices": [
      "顧客、競合、自店の強み・弱みなど経営環境を把握する",
      "売上目標を決めてから、顧客や競合の状況を目標に合わせて解釈する",
      "価格を変更して反応を見た後に、自店の強みと弱みを検討する",
      "設備投資額を先に決め、顧客層と提供価値は開業後に検討する"
    ],
    "answer": 0,
    "explanation": "経営戦略は、顧客ニーズ、市場、競合、自店の資源と強み・弱みを把握した上で目標と施策を定める。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "経営戦略は、顧客ニーズ、市場、競合、自店の資源と強み・弱みを把握した上で目標と施策を定める。",
    "themeId": "official_management_経営戦略"
  },
  {
    "id": 10042,
    "stableId": "追加-042",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "売上と利益",
    "q": "売上高と利益の関係について正しいものはどれか。",
    "choices": [
      "売上高から仕入額だけを差し引いた残りが最終利益となる",
      "売上高から費用を差し引いた残りが利益の基本となる",
      "売上高に費用を加えた額が利益の基本となる",
      "現金収入から現金支出だけを差し引いた額が常に利益となる"
    ],
    "answer": 1,
    "explanation": "利益は基本的に収益から費用を差し引いて求める。売上高が増えても費用がそれ以上に増えれば利益は増えない。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "利益は基本的に収益から費用を差し引いて求める。売上高が増えても費用がそれ以上に増えれば利益は増えない。",
    "themeId": "official_management_売上と利益"
  },
  {
    "id": 10043,
    "stableId": "追加-043",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "固定費・変動費",
    "q": "固定費の例として最も適切なものはどれか。",
    "choices": [
      "施術件数に応じて使用量が増えるシャンプー剤費",
      "販売個数に応じて増える店販商品の仕入原価",
      "売上の増減にかかわらず一定額が生じやすい店舗家賃",
      "売上高に一定率を掛けて支払う販売手数料"
    ],
    "answer": 2,
    "explanation": "店舗家賃は短期的には売上や施術件数にかかわらず一定額が生じやすい固定費の代表例である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "店舗家賃は短期的には売上や施術件数にかかわらず一定額が生じやすい固定費の代表例である。",
    "themeId": "official_management_固定費・変動費"
  },
  {
    "id": 10044,
    "stableId": "追加-044",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "損益分岐点",
    "q": "損益分岐点の説明として正しいものはどれか。",
    "choices": [
      "売上高と変動費が等しく、固定費分の損失が生じる点",
      "限界利益と売上高が等しく、利益が最大となる点",
      "売上高と固定費が等しく、変動費分の利益が生じる点",
      "売上高と総費用が等しく、利益が0となる点"
    ],
    "answer": 3,
    "explanation": "損益分岐点は、売上高と固定費・変動費の合計が等しく、利益も損失も生じない水準である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "損益分岐点は、売上高と固定費・変動費の合計が等しく、利益も損失も生じない水準である。",
    "themeId": "official_management_損益分岐点"
  },
  {
    "id": 10045,
    "stableId": "追加-045",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "資金繰り",
    "q": "黒字でも資金繰りが苦しくなる場合がある理由として適切なものはどれか。",
    "choices": [
      "売上の入金より支払が先になるなど、収支の時期がずれることがある",
      "利益は計上されていても、売上代金の回収前に支払期限が来ることがある",
      "売上代金を回収済みでも、減価償却費を計上すると現金が同額減る",
      "借入れを行うと利益が同額増えるため、返済時に資金だけが不足する"
    ],
    "answer": 0,
    "explanation": "利益は会計上の成果であり、現金の入出金時期とは一致しない。入金前の支払や借入返済、設備投資などで資金不足が起こり得る。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "利益は会計上の成果であり、現金の入出金時期とは一致しない。入金前の支払や借入返済、設備投資などで資金不足が起こり得る。",
    "themeId": "official_management_資金繰り"
  },
  {
    "id": 10046,
    "stableId": "追加-046",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "帳簿",
    "q": "経理帳簿を継続して記録する主な目的はどれか。",
    "choices": [
      "現金の入出金だけを記録し、利益と財産の状態を同一に扱うため",
      "経営成績と財政状態を把握し、申告や意思決定に役立てる",
      "申告時に売上だけを集計し、費用の記録を省略するため",
      "過去の数値を保存するだけで、経営判断には用いないため"
    ],
    "answer": 1,
    "explanation": "正確な帳簿は、売上・費用・資産・負債等を把握し、経営判断や税務申告の基礎となる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "正確な帳簿は、売上・費用・資産・負債等を把握し、経営判断や税務申告の基礎となる。",
    "themeId": "official_management_帳簿"
  },
  {
    "id": 10047,
    "stableId": "追加-047",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "社会保険",
    "q": "社会保険制度の説明として適切なものはどれか。",
    "choices": [
      "病気と老齢だけを対象とし、失業や業務災害は民間保険で支える仕組み",
      "労働者本人の拠出だけで、生活上のすべてのリスクを支える仕組み",
      "病気、老齢、失業、業務災害など生活上のリスクを社会全体で支える仕組みである",
      "事業主の任意加入だけにより、事業上の損失を補償する仕組み"
    ],
    "answer": 2,
    "explanation": "社会保険は、医療、年金、雇用、労災等を通じて生活上のリスクに備える仕組みである。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "shop",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・運営管理",
    "exp": "社会保険は、医療、年金、雇用、労災等を通じて生活上のリスクに備える仕組みである。",
    "themeId": "official_management_社会保険"
  },
  {
    "id": 10048,
    "stableId": "追加-048",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "健康保険",
    "q": "健康保険の給付対象として最も関係が深いものはどれか。",
    "choices": [
      "業務上の病気やけがに対する療養補償",
      "失業中の生活を支える基本手当",
      "老齢に伴う所得減少に対する年金給付",
      "業務外の病気やけが等に対する医療給付"
    ],
    "answer": 3,
    "explanation": "健康保険は、被保険者や被扶養者の業務外の病気・けが、出産、死亡等に関する給付を行う。",
    "difficulty": "標準",
    "sourceName": "全国健康保険協会「健康保険制度」",
    "sourceUrl": "https://www.kyoukaikenpo.or.jp/g3/",
    "category": "shop",
    "point": "全国健康保険協会「健康保険制度」",
    "exp": "健康保険は、被保険者や被扶養者の業務外の病気・けが、出産、死亡等に関する給付を行う。",
    "themeId": "official_management_健康保険"
  },
  {
    "id": 10049,
    "stableId": "追加-049",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "厚生年金保険",
    "q": "厚生年金保険の主な給付として適切なものはどれか。",
    "choices": [
      "老齢、障害、死亡に関する年金給付",
      "業務外の病気やけがに対する医療給付",
      "失業中の生活を支える基本手当",
      "業務上の災害に対する休業補償"
    ],
    "answer": 0,
    "explanation": "厚生年金保険は、老齢、障害、死亡に対する所得保障を行う公的年金制度である。",
    "difficulty": "標準",
    "sourceName": "日本年金機構「厚生年金保険」",
    "sourceUrl": "https://www.nenkin.go.jp/service/kounen/index.html",
    "category": "shop",
    "point": "日本年金機構「厚生年金保険」",
    "exp": "厚生年金保険は、老齢、障害、死亡に対する所得保障を行う公的年金制度である。",
    "themeId": "official_management_厚生年金保険"
  },
  {
    "id": 10050,
    "stableId": "追加-050",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "雇用保険",
    "q": "雇用保険の役割として適切なものはどれか。",
    "choices": [
      "業務上の災害に対する療養補償と休業補償を行う",
      "失業等給付や雇用の安定・能力開発を支える",
      "業務外の傷病に対する医療給付と傷病手当金を行う",
      "老齢、障害、死亡に関する年金給付を行う"
    ],
    "answer": 1,
    "explanation": "雇用保険は、労働者の失業等に対する給付と、雇用の安定・能力開発等を目的とする。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「雇用保険制度」",
    "sourceUrl": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_hoken.html",
    "category": "shop",
    "point": "厚生労働省「雇用保険制度」",
    "exp": "雇用保険は、労働者の失業等に対する給付と、雇用の安定・能力開発等を目的とする。",
    "themeId": "official_management_雇用保険"
  },
  {
    "id": 10051,
    "stableId": "追加-051",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "労働時間・休憩",
    "q": "労働時間が6時間を超え8時間以下の場合、労働基準法上必要な休憩時間は少なくとも何分か。",
    "choices": [
      "30分",
      "60分",
      "45分",
      "75分"
    ],
    "answer": 2,
    "explanation": "労働時間が6時間を超える場合は少なくとも45分、8時間を超える場合は少なくとも1時間の休憩を労働時間の途中に与える。",
    "difficulty": "標準",
    "sourceName": "ｅ－Ｇｏｖ法令検索「労働基準法」第34条",
    "sourceUrl": "https://laws.e-gov.go.jp/law/322AC0000000049",
    "category": "shop",
    "point": "ｅ－Ｇｏｖ法令検索「労働基準法」第34条",
    "exp": "労働時間が6時間を超える場合は少なくとも45分、8時間を超える場合は少なくとも1時間の休憩を労働時間の途中に与える。",
    "themeId": "official_management_労働時間・休憩"
  },
  {
    "id": 10052,
    "stableId": "追加-052",
    "status": "approved",
    "subjectId": "management",
    "subjectName": "運営管理",
    "field": "年次有給休暇",
    "q": "年次有給休暇について正しいものはどれか。",
    "choices": [
      "一定の勤続要件だけを満たせば、出勤率にかかわらず付与される",
      "正社員だけに付与され、短時間労働者には付与されない",
      "取得日は使用者が一方的に指定し、労働者は請求できない",
      "一定の要件を満たす労働者に法律上付与される"
    ],
    "answer": 3,
    "explanation": "年次有給休暇は、継続勤務期間と出勤率等の要件を満たす労働者に付与され、短時間労働者にも所定労働日数に応じて付与される。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「年次有給休暇」",
    "sourceUrl": "https://www.mhlw.go.jp/new-info/kobetu/roudou/gyousei/dl/140811-3.pdf",
    "category": "shop",
    "point": "厚生労働省「年次有給休暇」",
    "exp": "年次有給休暇は、継続勤務期間と出勤率等の要件を満たす労働者に付与され、短時間労働者にも所定労働日数に応じて付与される。",
    "themeId": "official_management_年次有給休暇"
  },
  {
    "id": 10053,
    "stableId": "追加-053",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "理容器具",
    "q": "クリッパーの用途として最も適切なものはどれか。",
    "choices": [
      "毛髪を能率的に短く切る",
      "毛髪の量を調整しながら、毛先を不ぞろいに切る",
      "毛髪を一定方向へとかし、切断線を確認する",
      "毛髪を挟んで熱を加え、一時的に形を整える"
    ],
    "answer": 0,
    "explanation": "クリッパーは、固定刃と動刃の作用により毛髪を短く切るための器具である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "クリッパーは、固定刃と動刃の作用により毛髪を短く切るための器具である。",
    "themeId": "official_barbering_theory_理容器具"
  },
  {
    "id": 10054,
    "stableId": "追加-054",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "理容器具",
    "q": "はさみの手入れとして適切なものはどれか。",
    "choices": [
      "刃に残った毛髪だけを除去し、水分は自然乾燥させる",
      "毛髪や水分を除去し、可動部や刃を適切に管理する",
      "切れ味を保つため、可動部のねじを常に強く締める",
      "刃面の汚れを落とすため、硬い器具でこすって研磨する"
    ],
    "answer": 1,
    "explanation": "使用後は付着物や水分を除去し、刃・ねじ・可動部を点検して適切に保守する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "使用後は付着物や水分を除去し、刃・ねじ・可動部を点検して適切に保守する。",
    "themeId": "official_barbering_theory_理容器具"
  },
  {
    "id": 10055,
    "stableId": "追加-055",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "理容器具",
    "q": "くしを選ぶ際の基本として適切なものはどれか。",
    "choices": [
      "毛髪の長さだけで選び、密度や技法は考慮しない",
      "技法だけで選び、歯の粗さや毛髪の状態は考慮しない",
      "毛髪の長さ、密度、技法に合う歯の粗さや形を選ぶ",
      "毛髪の密度だけで選び、材質や形はすべて同じものを用いる"
    ],
    "answer": 2,
    "explanation": "くしは用途、毛髪の状態、技法に応じ、歯の粗さ・長さ・形状・材質などを選ぶ。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "くしは用途、毛髪の状態、技法に応じ、歯の粗さ・長さ・形状・材質などを選ぶ。",
    "themeId": "official_barbering_theory_理容器具"
  },
  {
    "id": 10056,
    "stableId": "追加-056",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "理容器具",
    "q": "ヘアドライヤー使用時の注意として適切なものはどれか。",
    "choices": [
      "乾燥を早めるため、熱を一か所へ集中的に当てる",
      "毛髪との距離だけを保ち、温度や頭皮への熱は確認しない",
      "温度を一定に保つため、吹出口を毛髪へ密着させて動かす",
      "熱を一か所に当て続けず、頭皮との距離と温度に注意する"
    ],
    "answer": 3,
    "explanation": "熱傷や毛髪損傷、器具の過熱を防ぐため、距離・温度・時間・吸込口・電源コードに注意する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "熱傷や毛髪損傷、器具の過熱を防ぐため、距離・温度・時間・吸込口・電源コードに注意する。",
    "themeId": "official_barbering_theory_理容器具"
  },
  {
    "id": 10057,
    "stableId": "追加-057",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "基礎技術",
    "q": "施術者の姿勢として適切なものはどれか。",
    "choices": [
      "無理な前屈やねじれを避け、安定した姿勢で作業する",
      "施術部位へ近づくため、腰を曲げた姿勢を保って作業する",
      "器具を操作しやすくするため、上体をひねった姿勢を保つ",
      "客の姿勢を固定し、施術者は同じ位置から体を伸ばして作業する"
    ],
    "answer": 0,
    "explanation": "安定した姿勢と適切な作業位置は、施術の正確さと安全、施術者の疲労軽減につながる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "安定した姿勢と適切な作業位置は、施術の正確さと安全、施術者の疲労軽減につながる。",
    "themeId": "official_barbering_theory_基礎技術"
  },
  {
    "id": 10058,
    "stableId": "追加-058",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "シャンプー",
    "q": "シャンプー前の確認として適切なものはどれか。",
    "choices": [
      "毛髪の汚れだけを確認し、頭皮状態と既往施術は洗浄後に確認する",
      "頭皮・毛髪の状態、湯温、製品の適合を確認する",
      "製品の適合だけを確認し、湯温は客が訴えた場合に調整する",
      "頭皮状態と湯温だけを確認し、毛髪の損傷度は確認しない"
    ],
    "answer": 1,
    "explanation": "安全で効果的な洗髪には、頭皮・毛髪の状態、禁忌、湯温、使用製品、客の体調や希望を事前に確認する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "安全で効果的な洗髪には、頭皮・毛髪の状態、禁忌、湯温、使用製品、客の体調や希望を事前に確認する。",
    "themeId": "official_barbering_theory_シャンプー"
  },
  {
    "id": 10059,
    "stableId": "追加-059",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "シャンプー",
    "q": "シャンプー操作として適切なものはどれか。",
    "choices": [
      "洗浄力を高めるため、指先を立てて頭皮を細かくこする",
      "毛髪の摩擦を減らすため、頭皮を動かさず毛先だけを洗う",
      "爪を立てず、指腹を用いて頭皮を傷つけないように洗う",
      "頭皮への刺激を避けるため、洗浄剤をつけたまますすぎを短くする"
    ],
    "answer": 2,
    "explanation": "指腹を用いて適切な力で洗い、頭皮を傷つけず、洗浄剤を十分にすすぐ。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "指腹を用いて適切な力で洗い、頭皮を傷つけず、洗浄剤を十分にすすぐ。",
    "themeId": "official_barbering_theory_シャンプー"
  },
  {
    "id": 10060,
    "stableId": "追加-060",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "頭部処置",
    "q": "頭部マッサージの基本として適切なものはどれか。",
    "choices": [
      "筋肉への作用を高めるため、客の痛みを基準に強さを決める",
      "頭皮に炎症がある場合は、その周囲を強く刺激して血行を促す",
      "客の体調が良ければ、頭皮状態や禁忌の確認は省略する",
      "客の体調と頭皮状態を確認し、適切な強さで行う"
    ],
    "answer": 3,
    "explanation": "マッサージは客の体調、皮膚状態、禁忌を確認し、苦痛を与えない適切な強さとリズムで行う。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "マッサージは客の体調、皮膚状態、禁忌を確認し、苦痛を与えない適切な強さとリズムで行う。",
    "themeId": "official_barbering_theory_頭部処置"
  },
  {
    "id": 10061,
    "stableId": "追加-061",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "ヘアアイロン",
    "q": "ヘアアイロン使用時の基本として適切なものはどれか。",
    "choices": [
      "毛髪の状態に応じて温度と作用時間を調整する",
      "毛髪の太さだけで温度を決め、損傷度や作用時間は一定にする",
      "形を長く保つため、設定温度にかかわらず作用時間を長くする",
      "熱が均一に伝わるよう、毛髪の水分を残したまま高温で作用させる"
    ],
    "answer": 0,
    "explanation": "熱損傷を避けるため、毛髪の太さ・損傷・水分状態に応じて温度、時間、張力を調整する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "熱損傷を避けるため、毛髪の太さ・損傷・水分状態に応じて温度、時間、張力を調整する。",
    "themeId": "official_barbering_theory_ヘアアイロン"
  },
  {
    "id": 10062,
    "stableId": "追加-062",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "パーマ",
    "q": "パーマネントウェービングの基本原理として適切なものはどれか。",
    "choices": [
      "毛髪内の結合へ酸化だけを作用させ、軟化と形状変化を行う",
      "毛髪内の結合へ還元と酸化を作用させ、形を保持する",
      "毛髪表面の被膜を加熱して軟化させ、冷却だけで形を固定する",
      "毛髪内のメラニンを分解した後、染料の酸化で形を保持する"
    ],
    "answer": 1,
    "explanation": "パーマは還元剤で毛髪内の結合を切断し、ロッド等で形を与えた後、酸化剤で再結合させる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "パーマは還元剤で毛髪内の結合を切断し、ロッド等で形を与えた後、酸化剤で再結合させる。",
    "themeId": "official_barbering_theory_パーマ"
  },
  {
    "id": 10063,
    "stableId": "追加-063",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "パーマ",
    "q": "パーマ施術前の確認として適切なものはどれか。",
    "choices": [
      "毛髪の太さと長さだけを確認し、既往施術は薬剤選定後に確認する",
      "頭皮状態だけを確認し、毛髪の損傷度は作用時間で調整する",
      "毛髪の損傷度、既往施術、頭皮状態を確認する",
      "既往施術だけを確認し、製品の用法より希望する仕上がりを優先する"
    ],
    "answer": 2,
    "explanation": "薬剤反応と損傷リスクを見極めるため、毛髪診断、施術履歴、頭皮状態、製品の適用条件を確認する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "薬剤反応と損傷リスクを見極めるため、毛髪診断、施術履歴、頭皮状態、製品の適用条件を確認する。",
    "themeId": "official_barbering_theory_パーマ"
  },
  {
    "id": 10064,
    "stableId": "追加-064",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "ヘアカラー",
    "q": "ヘアカラーリング前の確認として適切なものはどれか。",
    "choices": [
      "過去に同じ色を使用していれば、製品が異なってもアレルギー歴の確認を省略する",
      "頭皮に異常がなければ、過去の染毛による全身症状は確認しない",
      "過去に異常がなくても、皮膚状態を確認せず毎回同じ条件で施術する",
      "製品表示、皮膚状態、過去のアレルギー反応等を確認する"
    ],
    "answer": 3,
    "explanation": "染毛剤はアレルギー等の危害を生じることがあるため、表示、使用前の注意、皮膚状態、既往反応を確認する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "染毛剤はアレルギー等の危害を生じることがあるため、表示、使用前の注意、皮膚状態、既往反応を確認する。",
    "themeId": "official_barbering_theory_ヘアカラー"
  },
  {
    "id": 10065,
    "stableId": "追加-065",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "ヘアカラー",
    "q": "染毛後の処置として適切なものはどれか。",
    "choices": [
      "薬剤が残らないよう、製品の手順に従って十分に洗い流す",
      "発色を安定させるため、少量の薬剤を毛髪に残して仕上げる",
      "洗浄による退色を防ぐため、すすぎは表面の薬剤が落ちた時点で終える",
      "残留薬剤を中和するため、製品の指定にない別薬剤を重ねてから洗い流す"
    ],
    "answer": 0,
    "explanation": "施術後は製品指示に従って薬剤を十分に除去し、頭皮・毛髪の状態と客の異常感を確認する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "施術後は製品指示に従って薬剤を十分に除去し、頭皮・毛髪の状態と客の異常感を確認する。",
    "themeId": "official_barbering_theory_ヘアカラー"
  },
  {
    "id": 10066,
    "stableId": "追加-066",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "エステティック",
    "q": "理容のエステティック技術を行う際の基本として適切なものはどれか。",
    "choices": [
      "施術目的と皮膚状態を確認し、体調は施術中の反応で判断する",
      "施術目的、客の体調、皮膚状態、禁忌を確認する",
      "客の希望があれば、禁忌に該当しても刺激の弱い方法で行う",
      "皮膚状態に異常がなければ、使用器具の衛生状態は施術後に確認する"
    ],
    "answer": 1,
    "explanation": "特殊技術でも、安全・衛生、適応と禁忌、客への説明と同意、使用器具・化粧品の適切な管理が必要である。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "特殊技術でも、安全・衛生、適応と禁忌、客への説明と同意、使用器具・化粧品の適切な管理が必要である。",
    "themeId": "official_barbering_theory_エステティック"
  },
  {
    "id": 10067,
    "stableId": "追加-067",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "ネイル",
    "q": "ネイル技術前の確認として適切なものはどれか。",
    "choices": [
      "爪に異常があっても、周囲皮膚に傷がなければ施術する",
      "周囲皮膚に異常があっても、爪甲に変化がなければ施術する",
      "爪と周囲皮膚の異常、傷、感染が疑われる所見を確認する",
      "感染が疑われても、器具を施術後に消毒すれば施術できる"
    ],
    "answer": 2,
    "explanation": "爪や周囲皮膚に異常、傷、感染が疑われる場合は施術可否を慎重に判断し、器具の衛生管理を徹底する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "爪や周囲皮膚に異常、傷、感染が疑われる場合は施術可否を慎重に判断し、器具の衛生管理を徹底する。",
    "themeId": "official_barbering_theory_ネイル"
  },
  {
    "id": 10068,
    "stableId": "追加-068",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "理容デザイン",
    "q": "ヘアデザインの要素として適切な組合せはどれか。",
    "choices": [
      "形、明度、彩度",
      "線、面、明暗",
      "形、方向、長さ",
      "形、質感、色彩"
    ],
    "answer": 3,
    "explanation": "ヘアデザインでは、輪郭やボリューム等の形、毛流や表面の質感、色彩を総合して構成する。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "ヘアデザインでは、輪郭やボリューム等の形、毛流や表面の質感、色彩を総合して構成する。",
    "themeId": "official_barbering_theory_理容デザイン"
  },
  {
    "id": 10069,
    "stableId": "追加-069",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "色彩",
    "q": "補色の関係について正しいものはどれか。",
    "choices": [
      "色相環で向かい合う関係の色",
      "色相環で隣り合う関係の色",
      "色相環で等間隔に三つ並ぶ関係の色",
      "同じ色相で明度だけが異なる関係の色"
    ],
    "answer": 0,
    "explanation": "補色は色相環でほぼ向かい合う関係にある色で、並べると互いを目立たせやすい。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "補色は色相環でほぼ向かい合う関係にある色で、並べると互いを目立たせやすい。",
    "themeId": "official_barbering_theory_色彩"
  },
  {
    "id": 10070,
    "stableId": "追加-070",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "色彩",
    "q": "明度の説明として正しいものはどれか。",
    "choices": [
      "色みの種類を表す度合い",
      "色の明るさの度合い",
      "色の鮮やかさを表す度合い",
      "色が暖かく又は冷たく感じられる度合い"
    ],
    "answer": 1,
    "explanation": "色の三属性は色相、明度、彩度であり、明度は色の明るさの度合いを表す。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "色の三属性は色相、明度、彩度であり、明度は色の明るさの度合いを表す。",
    "themeId": "official_barbering_theory_色彩"
  },
  {
    "id": 10071,
    "stableId": "追加-071",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "色彩",
    "q": "彩度の説明として正しいものはどれか。",
    "choices": [
      "色の明るさの度合い",
      "色みの種類を示す度合い",
      "色の鮮やかさの度合い",
      "色が暖かく又は冷たく感じられる度合い"
    ],
    "answer": 2,
    "explanation": "彩度は色の鮮やかさの度合いで、無彩色に近づくほど低くなる。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "彩度は色の鮮やかさの度合いで、無彩色に近づくほど低くなる。",
    "themeId": "official_barbering_theory_色彩"
  },
  {
    "id": 10072,
    "stableId": "追加-072",
    "status": "approved",
    "subjectId": "barbering_theory",
    "subjectName": "理容技術理論",
    "field": "総合判断",
    "q": "客に適した理容技術を選ぶ際の考え方として適切なものはどれか。",
    "choices": [
      "頭部・顔部の形態と流行を優先し、生活や要望は仕上げ時に調整する",
      "毛髪状態と安全性を優先し、客の要望や生活は技術選択に含めない",
      "客の要望と流行を優先し、頭部・顔部の形態や施術履歴は必要時だけ確認する",
      "頭部・顔部の形態、毛髪、生活、要望、安全性を総合して判断する"
    ],
    "answer": 3,
    "explanation": "技術選択は、客の要望、骨格・顔型、毛質・毛量、頭皮状態、生活、施術履歴、安全性を総合して行う。",
    "difficulty": "標準",
    "sourceName": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "sourceUrl": "https://www.mhlw.go.jp/content/11130500/001403710.pdf",
    "category": "cut",
    "point": "厚生労働省「理容師養成施設の教科課程の基準の運用について」・理容技術理論",
    "exp": "技術選択は、客の要望、骨格・顔型、毛質・毛量、頭皮状態、生活、施術履歴、安全性を総合して行う。",
    "themeId": "official_barbering_theory_総合判断"
  }
];
